name: Renovate
on:
  workflow_dispatch: # Allows manual triggering
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Renovate
        uses: renovatebot/github-action@41.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
